### ISSUE TITLE
Investigate Detecting changes in Amperage to determine when the climber has hit the mechanical hard stop

### ISSUE THREAD

**Issue by Sam-Malta** [cavineers/RobotCode2024#15]
Michael was talking about using this rather than using another sensor to determine when the motor is maxed out.

**Comment by Sam-Malta** [comment]
Thinking abt this a little more, this is a really kinda brutal way to detect it. We just run the motor full force into the hardtop...let's investigate adding a normal switch aswell

**Comment by BechtelLo25** [comment]
Discovered a weird bug where it only returns the amperage of the motor. Putting on backlog for now as it doesn't seem like a viable solution anyway.

**Comment by BechtelLo25** [comment]
Discovered a weird bug where it only returns the amperage of the motor sometimes. Putting on backlog for now as it doesn't seem like a viable solution anyway.

**Comment by Sam-Malta** [comment]
This got moved out of backlog, whats the status update? Is this planned and if so can you update the start and goal dates accordingly. Thanks

**Comment by roberts1y** [comment]
In progress. Date updated.

**Comment by Sam-Malta** [comment]
Believe this was finished + tested
@BechtelLo25 can confirm & update accordingly
