### ISSUE TITLE
5V 4Amp power supply from PDP

### ISSUE THREAD

**Issue by GitStudge** [cavineers/RobotCode2024#16]
We want to supply 5v 4A to the USB C port on the Orange Pi 5 so we can get max performance. Not necessary but definitely wanted.

**Comment by GitStudge** [comment]
We can use a buck converter to get the 4 amps that we're looking for. I have found 2 possible options but still need to talk to Dr. Waz about it. @Sam-Malta

**Comment by Sam-Malta** [comment]
Okay thanks matt

**Comment by Sam-Malta** [comment]
Listed as getting done today

Status @GitStudge

**Comment by Sam-Malta** [comment]
Pending delivery

**Comment by GitStudge** [comment]
> Pending delivery

We have a power supply in the workshop that is ready to be used. @Sam-Malta

**Comment by Sam-Malta** [comment]
i love matt studgeon
