### ISSUE TITLE
Put heatsinks on Orange Pi

### ISSUE THREAD

**Issue by GitStudge** [cavineers/RobotCode2024#18]

**Comment by roberts1y** [comment]
https://www.amazon.com/Case-Fit-Orange-Pi-Accessories/dp/B0BTRVKLN7/?_encoding=UTF8&pd_rd_w=WZa84&content-id=amzn1.sym.35cab78c-35e3-4fc1-aab0-27eaa6c86063%3Aamzn1.symc.e5c80209-769f-4ade-a325-2eaec14b8e0e&pf_rd_p=35cab78c-35e3-4fc1-aab0-27eaa6c86063&pf_rd_r=D1810MQAJ7TMKK5FM8KP&pd_rd_wg=UHrLM&pd_rd_r=a1fcf05d-fdae-42a6-9e54-6672049562fb&ref_=pd_gw_ci_mcx_mr_hp_atf_m

**Comment by Sam-Malta** [comment]
Done @GitStudge 

@mattheW0324 -- Did it
