### ISSUE TITLE
Auto Tasks

### ISSUE THREAD

**Issue by BechtelLo25** [cavineers/RobotCode2024#26]
To Do Before Movement Testing Auto

## Software
- [x] Orange Pi 5 Software Setup
- [x] Ardu Cams + Calibration
- [x] Multi-cam prediction

- [x] Multi tag prediction (AT)

## Hardware to Do
- [x] Orange Pi 5 Mounting
- [x] Camera Mounts

## Pending Arrival
- [x] Orange Pi 5
- [x] Arducams

**Comment by Sam-Malta** [comment]
Auto tasks have been delayed due to mechanical and hardware delays

Pending update from @GitStudge
