### ISSUE TITLE
Investigate implementation of advantage kit for competition logging

### ISSUE THREAD

**Issue by roberts1y** [cavineers/RobotCode2024#31]

**Comment by roberts1y** [comment]
https://www.chiefdelphi.com/t/introducing-logging-with-advantagekit/398612

**Comment by Sam-Malta** [comment]
I'll handle this after vision is solid for now

**Comment by Sam-Malta** [comment]
Implemented [2025 Framework](https://github.com/cavineers/Robot-Code-Framework-2025)

**Comment by roberts1y** [comment]
Is team 4541 using advantage kit?

**Comment by Sam-Malta** [comment]
yes its on the 2025 code repo
