### ISSUE TITLE
Talk to mechanical about sensors and shooter limitations

### ISSUE THREAD

**Issue by Sam-Malta** [cavineers/RobotCode2024#54]

**Comment by Sam-Malta** [comment]
Unsure if it's a problem yet
Intake has mini neos and Shooter has large neos
The concern is if the wheels aren't spinning at the same rate, then it creates a dragging effect. 
One solution could be to detect changes in amperage to large neos and then set the back wheels to free spin.

@Charles-M-Hecker

**Comment by Sam-Malta** [comment]
The current solution seems to be two IR sensors (not amperage) please talk to me on Monday abt this @Charles-M-Hecker

**Comment by Charles-M-Hecker** [comment]
Will talk with @Sam-Malta and mechanical on Monday about IR sensor placement
