### ISSUE TITLE
Start auto leveling command

### ISSUE THREAD

**Issue by Sam-Malta** [cavineers/RobotCode2024#59]

**Comment by ashley064** [comment]
We completed a draft of the autobalancing command today (on the climber_auto branch) that applies a PID loop to the right climber if the roll is positive or a PID loop to the left climber if the roll value is negative. We would like to test the code before making additional changes.

**Comment by ashley064** [comment]
2/24/24 Update: 
- Finished the auto-balancing command. It is now ready for review.
- Added a 2 degree threshold for the roll value (instead of applying a threshold to the u value - the output of the PID)
- Fine-tuned the kP value for the PID loop
- Tested the auto-balancing command
