### ISSUE TITLE
Basic Subsystem Setup Shooter -- Shooter

### ISSUE THREAD

**Issue by Sam-Malta** [cavineers/RobotCode2024#9]
Talked about on Jan 20. Planning on getting the setup and some functions of the Subsystem done by next Wednesday, possibly starting commands soon. Please keep this thread updated @Charles-M-Hecker

**Comment by Charles-M-Hecker** [comment]
Basic Subsystem with feeder, intake, and shooter motors completed. Starting commands on Jan 24. Awaiting review

**Comment by Sam-Malta** [comment]
Completed
1.27
